### ISSUE TITLE
View district permission error when using checklist export. 

### ISSUE THREAD

**Issue by sgodbehere01** [davosmith/moodle-grade_checklist#3]
Hello, I've posted the below on the Moodle tracker but just thought I'd post it here as well for visibility as it seems to be specifically an issue with checklist_export, if that's an issue feel free to close or remove:

Hi there,

We seem to have encountered an issue with the export checklist feature when a user has the permission to view all users in their group but not all users.

To reproduce:

    Enrol test user onto a test course with a role with the "gradeexport/checklist:viewdistrict" permission. (In our case we have a role separate from student that grants this permission, but granting the permission as an override for the course or to the student role itself doesn't seem to work in any case).

    Confirm the user should have the "gradeexport/checklist:viewdistrict" permission in "Check permissions".

    Add a checklist with an activity assigned to it as per normal.

    Logged in as test user go to Grades -> Export -> Export Excel file.

    At this point the error should appear: "You do not have permission to do this export".

If you grant the user the view all users permission rather than or in addition to the view district permission this works in that case.

In the server logs the error appears as a fairly typical Moodle permission error:

Default exception handler: You do not have permission to do this export Debug: \nError code: nopermission\n* line 494 of /lib/setuplib.php: moodle_exception thrown\n* line 51 of /grade/export/checklist/export.php: call to print_error()\n, referer: https://www.ourmoodle.com/grade/export/checklist/index.php?id=492

It would appear to be an issue introduced after upgrading to Moodle 3.6.5.

Let us know if you need any more details regarding our testing/settings with this issue or if you are having issues replicating it.

Kind regards,

Sam

**Comment by davosmith** [comment]
Please can you confirm that you have added a custom user profile field called 'district' to your site, in order to use this feature? If there is no such field, then the error is quite correct (because a user who cannot view all users will require the 'view district' capability AND to have a district configured).

The logic for this hasn't changed since this worked with Moodle 1.9 - I'd be very surprised if this was an issue introduced in Moodle 3.6.

Also, could you provide a link to the Moodle tracker issue, as I haven't been automatically notified about it (which I would expect if you'd opened a ticket against graeexport_checklist).
